export const featurePillars = [
  {
    kicker: "Deterministic Engine",
    title: "Recommendations you can trust and explain",
    description:
      "TravelTom blends retrieval and ranking so every suggestion is traceable, reproducible, and easier to compare.",
  },
  {
    kicker: "Constraint-Aware",
    title: "Built for real-world travel constraints",
    description:
      "Budget, dates, preferences, and trip style are captured in chat and applied through the full planning flow.",
  },
  {
    kicker: "Planning Workflow",
    title: "From discovery to shortlist in one place",
    description:
      "Move from conversation to recommended destinations, hotels, and flights without jumping across tools.",
  },
] as const;

export const planningSteps = [
  {
    step: "01",
    title: "Share your trip goals",
    description:
      "Tell TravelTom where you are leaving from, your dates, and what kind of experience you want.",
  },
  {
    step: "02",
    title: "Review ranked options",
    description:
      "Get destination, hotel, and flight suggestions with scoring and concise explanations.",
  },
  {
    step: "03",
    title: "Build your shortlist",
    description:
      "Save the best options and assemble an itinerary draft that is ready for refinement.",
  },
] as const;

export const recommendationPreview = [
  {
    itemType: "destination",
    title: "Lisbon, Portugal",
    detail: "Culture-forward city break with coastal day trips",
    rank: "#1",
  },
  {
    itemType: "hotel",
    title: "Solaris Riverside Hotel",
    detail: "4.7 rating, central location, breakfast included",
    rank: "#2",
  },
  {
    itemType: "flight",
    title: "JFK -> LIS",
    detail: "1 stop, 10h 35m, balanced price and duration",
    rank: "#3",
  },
] as const;

export const authPageContent = {
  login: {
    eyebrow: "Welcome Back",
    title: "Pick up your next trip where you left it.",
    description:
      "Sign in to reopen your planner, review ranked options, and continue refining the trip without losing momentum.",
    alternateLabel: "Need a TravelTom account?",
    alternateCta: "Create one",
    panelTitle: "What waits inside",
    panelBody:
      "The planner keeps the workflow focused: conversation in one pane, ranked picks in the other, and every recommendation tied to your travel constraints.",
    reassurance:
      "Use the same email and password you created for TravelTom local auth.",
  },
  signup: {
    eyebrow: "Create Your Account",
    title: "Start planning with a calmer, faster travel flow.",
    description:
      "Create an account to move from open-ended trip ideas into a workspace built for destination discovery, hotel comparison, and flight decisions.",
    alternateLabel: "Already have an account?",
    alternateCta: "Sign in",
    panelTitle: "Why sign up now",
    panelBody:
      "TravelTom turns scattered travel research into a single planning rhythm, with clear recommendations and a direct path into the planner.",
    reassurance:
      "Accounts use TravelTom email and password auth today. No extra verification step is required in this flow.",
  },
  highlights: [
    "Deterministic recommendations you can compare quickly",
    "Constraint-aware ranking across destinations, hotels, and flights",
    "A clear route back to the landing page whenever you want to reset your path",
  ],
} as const;

export const systemFlowSteps = [
  {
    title: "Capture intent",
    detail:
      "Chat captures destinations, budget, dates, and preferences with explicit user constraints.",
  },
  {
    title: "Retrieve candidates",
    detail:
      "The backend retrieves viable destination, hotel, and flight candidates from the catalog.",
  },
  {
    title: "Rank deterministically",
    detail:
      "A deterministic ranker scores and orders options with transparent explanations per item.",
  },
  {
    title: "Return actionable output",
    detail:
      "The frontend receives ranked items, then drives shortlist and itinerary flows from that output.",
  },
] as const;

export const whyTrustSignals = [
  {
    title: "Deterministic by default",
    detail:
      "Recommendations are generated by a reproducible service layer, not guessed by the LLM.",
  },
  {
    title: "Tool-first orchestration",
    detail:
      "The assistant orchestrates tools and schemas, keeping decision logic explicit and testable.",
  },
  {
    title: "Event-driven iteration",
    detail:
      "Impressions, clicks, saves, and booking actions are tracked for measurable product improvement.",
  },
] as const;

export function getApiStatusText(isSuccess: boolean, isError: boolean): string {
  if (isSuccess) {
    return "API online";
  }
  if (isError) {
    return "API unreachable";
  }
  return "API checking";
}
