export const featurePillars = [
  {
    kicker: "Deterministic Engine",
    title: "Recommendations you can trust and explain",
    description:
      "TravelTom blends retrieval and ranking so every suggestion is traceable, reproducible, and easier to compare.",
  },
  {
    kicker: "Constraint-Aware",
    title: "Built for real-world travel constraints",
    description:
      "Budget, dates, preferences, and trip style are captured in chat and applied through the full planning flow.",
  },
  {
    kicker: "Planning Workflow",
    title: "From discovery to shortlist in one place",
    description:
      "Move from conversation to recommended destinations, hotels, and flights without jumping across tools.",
  },
] as const;

export const planningSteps = [
  {
    step: "01",
    title: "Share your trip goals",
    description:
      "Tell TravelTom where you are leaving from, your dates, and what kind of experience you want.",
  },
  {
    step: "02",
    title: "Review ranked options",
    description:
      "Get destination, hotel, and flight suggestions with scoring and concise explanations.",
  },
  {
    step: "03",
    title: "Build your shortlist",
    description:
      "Save the best options and assemble an itinerary draft that is ready for refinement.",
  },
] as const;

export const recommendationPreview = [
  {
    itemType: "destination",
    title: "Lisbon, Portugal",
    detail: "Culture-forward city break with coastal day trips",
    rank: "#1",
  },
  {
    itemType: "hotel",
    title: "Solaris Riverside Hotel",
    detail: "4.7 rating, central location, breakfast included",
    rank: "#2",
  },
  {
    itemType: "flight",
    title: "JFK -> LIS",
    detail: "1 stop, 10h 35m, balanced price and duration",
    rank: "#3",
  },
] as const;

export const systemFlowSteps = [
  {
    title: "Capture intent",
    detail:
      "Chat captures destinations, budget, dates, and preferences with explicit user constraints.",
  },
  {
    title: "Retrieve candidates",
    detail:
      "The backend retrieves viable destination, hotel, and flight candidates from the catalog.",
  },
  {
    title: "Rank deterministically",
    detail:
      "A deterministic ranker scores and orders options with transparent explanations per item.",
  },
  {
    title: "Return actionable output",
    detail:
      "The frontend receives ranked items, then drives shortlist and itinerary flows from that output.",
  },
] as const;

export const whyTrustSignals = [
  {
    title: "Deterministic by default",
    detail:
      "Recommendations are generated by a reproducible service layer, not guessed by the LLM.",
  },
  {
    title: "Tool-first orchestration",
    detail:
      "The assistant orchestrates tools and schemas, keeping decision logic explicit and testable.",
  },
  {
    title: "Event-driven iteration",
    detail:
      "Impressions, clicks, saves, and booking actions are tracked for measurable product improvement.",
  },
] as const;

export function getApiStatusText(isSuccess: boolean, isError: boolean): string {
  if (isSuccess) {
    return "API online";
  }
  if (isError) {
    return "API unreachable";
  }
  return "API checking";
}
