"""Shared schema models for orchestration responses and runtime payloads."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.schemas.state import BudgetRange, DateRange, PartySize
from app.schemas.tools.recommendations import (
    RecommendationResult,
    RecommendationToolResponse,
)

Intent = Literal["recommend", "refine", "clarify"]
SessionStatus = Literal["explore", "refine", "itinerary", "booking"]


@dataclass(frozen=True)
class OrchestratorPolicyConfig:
    """Static policy settings for orchestrator runtime behavior."""

    recommendation_timeout_seconds: float = 4.0
    max_recommendation_results: int = 5
    recent_history_message_limit: int = 6


@dataclass(frozen=True)
class OrchestrationDecision:
    """Output of deterministic guardrail logic before tool execution."""

    intent: Intent
    should_call_recommendation_tool: bool
    reason: str


class ConstraintPatch(BaseModel):
    """LLM-proposed updates for ``SessionState.constraints``."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    origin: str | None = None
    destination: str | None = None
    dates: DateRange | None = None
    trip_length_days: int | None = Field(default=None, ge=1)
    budget: BudgetRange | None = None
    party_size: PartySize | None = None


class PreferencePatch(BaseModel):
    """LLM-proposed updates for ``SessionState.preferences``."""

    model_config = ConfigDict(extra="forbid")

    weighted_interests: dict[str, float] | None = None
    dislikes: list[str] | None = None

    @field_validator("weighted_interests")
    @classmethod
    def validate_interest_weights(
        cls,
        values: dict[str, float] | None,
    ) -> dict[str, float] | None:
        if values is None:
            return None
        for key, value in values.items():
            if not 0 <= value <= 1:
                raise ValueError(f"weighted_interests[{key}] must be between 0 and 1")
        return values


class EntityPatch(BaseModel):
    """LLM-proposed updates for ``SessionState.entities``."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    destinations: list[str] | None = None


class RecommendationQueryControls(BaseModel):
    """LLM-suggested query controls mapped to ``RecommendationQuery``."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    query: str | None = None
    filters: dict[str, Any] = Field(default_factory=dict)
    max_results: int | None = Field(default=None, ge=1, le=50)


class PlannerConversationPatch(BaseModel):
    """LLM-proposed conversation metadata (transient planner hints)."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    last_requested_slots: list[str] | None = None
    last_user_intent: Intent | None = None
    last_clarification_kind: (
        Literal[
            "core_slot",
            "search_type",
            "refine_preference",
            "greeting",
        ]
        | None
    ) = None
    last_search_outcome: (
        Literal[
            "results",
            "empty_results",
            "no_new_results",
        ]
        | None
    ) = None
    last_recommendation_item_type: Literal["hotel", "restaurant", "activity"] | None = (
        None
    )
    last_recommendation_query: str | None = None


class OrchestrationStatePatch(BaseModel):
    """LLM state patch merged into the persisted ``SessionState``."""

    model_config = ConfigDict(extra="forbid")

    constraints: ConstraintPatch | None = None
    preferences: PreferencePatch | None = None
    entities: EntityPatch | None = None
    status: SessionStatus | None = None
    conversation: PlannerConversationPatch | None = Field(
        default=None,
        exclude=True,
    )
    query_controls: RecommendationQueryControls | None = Field(
        default=None,
        exclude=True,
    )


class LLMOrchestrationPlan(BaseModel):
    """Structured planner output generated by the LLM."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    intent: Intent
    should_call_recommendation_tool: bool
    clarification_message: str | None = None
    state_patch: OrchestrationStatePatch = Field(
        default_factory=OrchestrationStatePatch
    )
    query_controls: RecommendationQueryControls = Field(
        default_factory=RecommendationQueryControls
    )

    @model_validator(mode="after")
    def coerce_query_controls_from_state_patch(self) -> "LLMOrchestrationPlan":
        """Support planner payloads that nest query_controls inside state_patch."""

        nested = self.state_patch.query_controls
        if nested is None:
            return self

        self.query_controls = RecommendationQueryControls(
            query=(
                self.query_controls.query
                if self.query_controls.query is not None
                else nested.query
            ),
            filters={
                **nested.filters,
                **self.query_controls.filters,
            },
            max_results=(
                self.query_controls.max_results
                if self.query_controls.max_results is not None
                else nested.max_results
            ),
        )
        return self


class LLMComposedResponse(BaseModel):
    """Structured LLM response used for final assistant copy."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    assistant_message: str = Field(min_length=1)


class TranscriptMessage(BaseModel):
    """Bounded persisted transcript item used for orchestration context."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    role: Literal["user", "assistant"]
    content: str = Field(min_length=1)


class RecommendationToolRuntimePayload(BaseModel):
    """Normalized artifact returned by the LangChain recommendation tool."""

    model_config = ConfigDict(extra="forbid")

    status: Literal["success", "timeout", "invalid_payload", "failure"]
    response: RecommendationToolResponse | None = None
    error_code: str | None = None
    error_message: str | None = None


class OrchestratorDiagnostics(BaseModel):
    """Per-turn diagnostics for planner/composer usage and fallback behavior."""

    model_config = ConfigDict(str_strip_whitespace=True)

    provider: Literal["disabled", "ollama", "phi35mini", "openai"] | None = None
    planner_attempted: bool = False
    planner_used: bool = False
    planner_status: str = "not_requested"
    composer_attempted: bool = False
    composer_used: bool = False
    composer_status: str = "not_requested"
    fallback_reason: str | None = None
    degraded: bool = False


class OrchestratorResponse(BaseModel):
    """Normalized orchestrator output for API layer integration."""

    session_id: str
    assistant_message: str
    recommendations: list[RecommendationResult] = Field(default_factory=list)
    itinerary: dict[str, Any] = Field(default_factory=dict)
    state: dict[str, Any]
    diagnostics: OrchestratorDiagnostics = Field(
        default_factory=OrchestratorDiagnostics
    )
